icepalace/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

icepalace/icepalace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from account.admin import custom_admin_site
from account import views as account_views, views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', account_views.register_view, name='register'),
    path('login/', account_views.login_view, name='login'),
    path('logout/', account_views.logout_view, name='logout'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('palace.urls', namespace='palace')),
    path('palace/home.html', views.palace_base_view, name='palace_base'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

icepalace/payment/urls.py
from django.urls import path
from . import views
from . import webhooks

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('completed/', views.payment_completed, name='completed'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('webhook/', webhooks.stripe_webhook, name='stripe-webhook'),
]

icepalace/payment/models.py
from django.db import models

# Create your models here.

icepalace/payment/views.py
from decimal import Decimal
import stripe
from django.conf import settings
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from orders.models import Order, OrderItem

#создаю экземпляр stripe
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


@csrf_exempt
def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        cansel_url = request.build_absolute_uri(reverse('payment:canceled'))
        #данные для создания платежа
        session_data = {'mode': 'payment',
                        'client_reference_id': order_id,
                        'success_url': success_url,
                        'cancel_url': cansel_url,
                        'line_items': []
                        }
        #добавляю услуги заказа в платеж
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.price * Decimal('100')),
                    'currency': 'rub',
                    'product_data': {
                        'name': item.product.name,
                    },
                },
                'quantity': item.quantity,
            })
        #создаю сеанс оформления платежа
        session = stripe.checkout.Session.create(**session_data)
        #перенаправляю на страницу оплаты
        return redirect(session.url, code=303)
    else:
        return render(request, 'payment/process.html', locals())


def payment_completed(request):  # успешный платеж
    return render(request, 'payment/completed.html')


def payment_canceled(request):  # отмена платежа
    return render(request, 'payment/canceled.html')

icepalace/payment/templates/payment/canceled.html
{% extends 'palace/base.html'%}
{% block title%}Платеж отменен{%endblock%}

{% block content %}
<h1>Ваш платеж отменен</h1>
{% endblock %}

icepalace/payment/templates/payment/completed.html
{% extends 'palace/base.html'%}
{% block title%}Успешная оплата{%endblock%}
{%block content%}
    <h1>Вы успешно оплатили заказ!</h1>
    <p>Ваш платеж принят.</p>
{%endblock%}

icepalace/payment/templates/payment/process.html
{% extends 'palace/base.html' %}
{% load static %}

{% block title %} Оплата вашего заказа {% endblock %}

{% block content %}

<h1>Описание заказа</h1>
<table class="cart">
    <thead>
        <tr>
            <th>Изображение</th>
            <th>Наименование услуги</th>
            <th>Цена</th>
            <th>Количество</th>
            <th>Итого</th>
        </tr>
    </thead>
    <tbody>
        {% for item in order.items.all %}
             <tr class="row{% cycle "1" "2" %}">
                  <td><img src="{% if item.product.image %}{{ item.product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"></td>
                  <td>{{ item.product.name }}</td>
                  <td class="num">{{ item.price }} руб.</td>
                  <td class="num">{{ item.quantity }}</td>
                  <td class="num">{{ item.get_cost }} руб.</td>
             </tr>
        {% endfor %}
        <tr class="total">
            <td colspan="4">Итого:</td>
            <td class="num">{{ order.get_total_cost }} руб.</td>
        </tr>
    </tbody>
    </table>
<form action="{% url "payment:process" %}" method="post">
    <input type="submit" value="Оплатить">
    {% csrf_token %}
</form>
{% endblock %}