icepalace/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

icepalace/icepalace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from account.admin import custom_admin_site
from account import views as account_views, views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', account_views.register_view, name='register'),
    path('login/', account_views.login_view, name='login'),
    path('logout/', account_views.logout_view, name='logout'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('palace.urls', namespace='palace')),
    path('palace/home.html', views.palace_base_view, name='palace_base'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

icepalace/palace/urls.py
from django.urls import path
from . import views


app_name = 'palace'

urlpatterns = [

    path('', views.home, name='home'),
    path('shedule/', views.shedule_list, name='shedule_list'),
    path('shedule/<int:id>/<slug:slug>/', views.shedule_detail, name='shedule_detail'),
    path('products/', views.product_list, name='product_list'),
    path('products/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),



]

icepalace/palace/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name='Категория')
    slug = models.CharField(max_length=200, unique=True, verbose_name='Слаг')

    class Meta:
        ordering = ['name']  # сортировка по имени
        indexes = [models.Index(fields=['name']), ]
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):# создание URL-адреса для категории
        return reverse('palace:product_list_by_category', args=[self.slug])


class Product(models.Model):
    # связь один ко многим - одна категория много товаров
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, verbose_name='Категория')
    name = models.CharField(max_length=200, verbose_name='Услуга')
    # слаг этого товара для создания красивых URL-адресов
    slug = models.CharField(max_length=200, verbose_name='Слаг')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name='Изображение')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    # наличие или отсутствие товара
    available = models.BooleanField(default=True, verbose_name='Доступен')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['id', 'slug']),
                   models.Index(fields=['name']),
                   models.Index(fields=['-created']),
                   ]
        verbose_name = 'услуга'
        verbose_name_plural = 'услуги'

    def __str__(self):# вывод названия товара
        return self.name

    def get_absolute_url(self):# создание URL-адреса для товара
        return reverse('palace:product_detail', args=[self.id, self.slug])


class Shedule(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название мероприятия')
    time_event = models.DateTimeField(verbose_name='Время мероприятия')
    slug = models.CharField(max_length=200, verbose_name='Слаг')

    class Meta:
        ordering = ['time_event']
        indexes = [models.Index(fields=['id', 'slug']),
                   models.Index(fields=['name']),
                   models.Index(fields=['-time_event']),
                   ]
        verbose_name = 'мероприятие'
        verbose_name_plural = 'мероприятия'

    def __str__(self):# вывод названия мероприятия
        return self.name

    def get_absolute_url(self):# создание URL-адреса для мероприятия
        return reverse('palace:shedule_detail', args=[self.id, self.slug])

icepalace/palace/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.shortcuts import render
from .models import Shedule
from django.core.paginator import Paginator
from django.db.models import Q
from datetime import datetime


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'palace/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'palace/product/detail.html',
                  {'product': product, 'cart_product_form': cart_product_form})


def shedule_detail(request, id, slug):
    event = get_object_or_404(Shedule, id=id, slug=slug)
    return render(request, 'palace/shedule_detail.html', {'event': event})

def shedule_list(request):
    date_filter = request.GET.get('date')

    queryset = Shedule.objects.all()

    if date_filter:
        try:
            filter_date = datetime.strptime(date_filter, '%Y-%m-%d:%H:%M').date()
            queryset = queryset.filter(
                Q(time_event__date=filter_date) |
                Q(time_event__date__gt=filter_date)
            )
        except ValueError:
            pass

    queryset = queryset.order_by('time_event')
    # Получаем все мероприятия, отсортированные по времени
    all_events = Shedule.objects.all().order_by('time_event')

    # Пагинация - по 10 мероприятий на страницу
    paginator = Paginator(all_events, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'current_date': timezone.now().date()  # Текущая дата для сравнения
    }
    return render(request, 'palace/shedule_list.html', context)


def home(request):
    categories = Category.objects.all()
    return render(request, 'palace/home.html', {'categories': categories})#

icepalace/palace/templates/includes/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="{% url 'palace:home' %}">Ледовый Дворец</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'palace:home' %}">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'palace:shedule_list' %}">Расписание</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown">
            Товары
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'palace:product_list' %}">Все товары</a></li>
            {% for category in Category.objects.all %}
              <li><a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
            {% endfor %}
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}">Корзина</a>
        </li>
        <li class="nav-item">
          <span class="nav-link text-white">Вы вошли как: {{ user.username }}</span>
        </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Войти</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>